name: golangci-lint
on:
  push:
    tags:
    - v*
    branches:
    - main
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci-sg:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version-file: "go.mod"
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        only-new-issues: true